## 섹션 11. 예외 처리2 - 실습

### 1. 예외 처리 도입1 - 시작
- 예외 처리 도입 전
```
  public String connect() {
        // 연결 실패
        if (connectError) {
            System.out.println(address + " 서버 연결 실패");
            return "connectError";
        }
        // 연결 성공
        System.out.println(address + " 서버 연결 성공");
        return "success";
    }
```
- 예외 처리 도입 
```
 public void connect() throws NetworkClientExceptionV2{
        // 연결 실패
        if (connectError) {
            throw new NetworkClientExceptionV2("connectError", address + " 서버 연결 실패" );
        }
        // 연결 성공
        System.out.println(address + " 서버 연결 성공");
    }
```
- 오류가 발생했을 때 오류코드를 반환하는 것이 아니라 예외를 던진다.
- 예외가 main() 밖으로 던져지면 예외 정보와 스택 트레이스(Stack Trace)를 출력하고 프로그램이 종료된다.


### 2. 예외 처리 도입2 - 예외 복구

```
 try {
            client.connect();
        } catch (NetworkClientExceptionV2 e) {
            System.out.println("[오류] 코드: " + e.getErrorCode() + ", 메시지: " + e.getMessage());
            return;
        }

        try {
            client.send(data);
        } catch (NetworkClientExceptionV2 e) {
            System.out.println("[오류] 코드: " + e.getErrorCode() + ", 메시지: " + e.getMessage());
            return;
        }
        client.disconnect();
```

### 3. 예외 처리 도입3 - 정상, 예외 흐름 분리 
```
try {
            client.connect();
            client.send(data);
            client.disconnect();
        } catch (NetworkClientExceptionV2 e) {
            System.out.println("[오류] 코드: " + e.getErrorCode() + ", 메시지: " + e.getMessage());
        }
```

자바의 예외처리 매커니즘과 try, catch 구조 덕분에 정상 흐름은 try 블럭에 모아서 처리하고 예외 흐름은 catch 블럭에 별도로 모아서 처리함


### 4. 예외 처리 도입4 - 리소스 반환 문제

disconnect() 메서드를 꼭 실행하도록 수정해보자.
```
try {
            client.connect();
            client.send(data);
        } catch (NetworkClientExceptionV2 e) {
            System.out.println("[오류] 코드: " + e.getErrorCode() + ", 메시지: " + e.getMessage());
        }                   
        client.disconnect();
```
이 코드의 문제점 : NetworkClientExceptionV2 예외가 아닌 다른 예외가 발생한다면 catch 의 대상이 되지못해 밖으로 던져진다.


### 5. 예외 처리 도입5 - finally
`자바는 어떤 경우라도 반드시 호출되는 finally 기능을 제공한다.`
```
try { 
    // 정상 흐름
} catch { 
    // 예외 흐름 
} finally {
    // 반드시 호출해야 하는 마무리 흐름 
}
```
- try ~ catch ~ finally 구조는 정상 흐름, 예외 흐름, 마무리 흐름을 제공한다.
- try ~ catch ~ finally 구조의 장점
  - 정상 흐름과 예외 흐름을 분리해서, 코드를 읽기 쉽게 만든다.
  - 사용한 자원을 항상 반환할 수 있도록 보장해준다.

#### 처리할 수 없는 예외와 finally
- 심지어 try, catch 안에서 잡을 수 없는 예외가 발생해도(던져도) finally 는 반드시 호출된다.
- try, catch 안에서 잡을 수 없는 예외가 발생해서, 예외를 밖으로 던지는 경우에도 finally 를 먼저 호출하고 나서 예
    외를 밖으로 던진다.



### 6. 예외 계층 - 시작
### 7. 예외 계층 - 활용

